# Generated by Django 6.0 on 2026-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Ссылка на картинку постера'),
        ),
        migrations.AddField(
            model_name='item',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на трейлер (YouTube)'),
        ),
    ]
